version: '3'

services:
  mock-api:
    image: "wiremock/wiremock:3.5.2"
    ports:
      - "8081:8081"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
    entrypoint: ["/docker-entrypoint.sh", "--port=8081"]
  database:
    image: "postgres:16-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=irrigation
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  application:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=database
      - DB_NAME=irrigation
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - WEATHER_API_URL=http://mock-api:8081
    ports:
      - "8080:8080"
    depends_on:
      - mock-api
      - database
